# Generated by Django 3.1.1 on 2020-09-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200914_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='Todo',
        ),
    ]
