# Generated by Django 3.1.1 on 2020-09-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200914_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_date',
            new_name='Date',
        ),
    ]
